//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EClerx.WebAPI.Demo1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Department
    {
        public string cDepartmentCode { get; set; }
        public string vDepartmentName { get; set; }
        public string vDepartmentHead { get; set; }
        public string vLocation { get; set; }
    }
}
